- name: Install vagrant
  become: True
  package:
    state: present
    name:
    - vagrant
    - vagrant-libvirt
    - vagrant-sshfs

- name: Install required packages
  become: True
  package:
    state: present
    name:
    - dnsmasq
    - libvirt
    - NetworkManager
